### ISSUE TITLE
这种东西还是别扔到Git上了吧

### ISSUE THREAD

**Issue by FujiZ** [puppylpg/CompilerDesign#1]
万一被人拿去抄了怎么办。。。

**Comment by puppylpg** [comment]
怕电脑崩了，也怕自己把代码改崩了，而且这种东西，爱抄抄吧，又不是机密，也没啥好抄的。。。

**Comment by FujiZ** [comment]
可以放coding上呀，我就是扔那上面的

**Comment by puppylpg** [comment]
习惯了github的界面了，感觉很爽，不过也行，也可以往coding.net上扔一份儿
